-- AlterTable
ALTER TABLE `booking` ADD COLUMN `updatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `customer` ADD COLUMN `updatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` ADD COLUMN `updatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
